/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhaleHunterRouteImport } from './routes/whale-hunter'
import { Route as WeatherIntelRouteImport } from './routes/weather-intel'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SealcoatingRouteImport } from './routes/sealcoating'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RoofingRouteImport } from './routes/roofing'
import { Route as ResidentialRouteImport } from './routes/residential'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MasonryRouteImport } from './routes/masonry'
import { Route as GcBidRouteImport } from './routes/gc-bid'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConcreteRouteImport } from './routes/concrete'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as LocationsWindsorFarmsRouteImport } from './routes/locations/windsor-farms'
import { Route as LocationsWilliamsburgRouteImport } from './routes/locations/williamsburg'
import { Route as LocationsWesthamParkwayRouteImport } from './routes/locations/westham-parkway'
import { Route as LocationsWarrentonRouteImport } from './routes/locations/warrenton'
import { Route as LocationsVirginiaBeachRouteImport } from './routes/locations/virginia-beach'
import { Route as LocationsTuckahoeRouteImport } from './routes/locations/tuckahoe'
import { Route as LocationsSussexRouteImport } from './routes/locations/sussex'
import { Route as LocationsSuffolkRouteImport } from './routes/locations/suffolk'
import { Route as LocationsStratfordHillsRouteImport } from './routes/locations/stratford-hills'
import { Route as LocationsStandardsRouteImport } from './routes/locations/standards'
import { Route as LocationsStaffordRouteImport } from './routes/locations/stafford'
import { Route as LocationsSpotsylvaniaRouteImport } from './routes/locations/spotsylvania'
import { Route as LocationsShortPumpRouteImport } from './routes/locations/short-pump'
import { Route as LocationsSandstonRouteImport } from './routes/locations/sandston'
import { Route as LocationsRichmondRouteImport } from './routes/locations/richmond'
import { Route as LocationsResidentialRouteImport } from './routes/locations/residential'
import { Route as LocationsPrinceWilliamRouteImport } from './routes/locations/prince-william'
import { Route as LocationsPrinceGeorgeRouteImport } from './routes/locations/prince-george'
import { Route as LocationsPowhatanRouteImport } from './routes/locations/powhatan'
import { Route as LocationsPortsmouthRouteImport } from './routes/locations/portsmouth'
import { Route as LocationsPetersburgRouteImport } from './routes/locations/petersburg'
import { Route as LocationsOrangeRouteImport } from './routes/locations/orange'
import { Route as LocationsNorfolkRouteImport } from './routes/locations/norfolk'
import { Route as LocationsNewportnewsRouteImport } from './routes/locations/newportnews'
import { Route as LocationsNewKentRouteImport } from './routes/locations/new-kent'
import { Route as LocationsMoseleyRouteImport } from './routes/locations/moseley'
import { Route as LocationsMidlothianRouteImport } from './routes/locations/midlothian'
import { Route as LocationsMechanicsvilleRouteImport } from './routes/locations/mechanicsville'
import { Route as LocationsMcleanRouteImport } from './routes/locations/mclean'
import { Route as LocationsLouisaRouteImport } from './routes/locations/louisa'
import { Route as LocationsLakesideRouteImport } from './routes/locations/lakeside'
import { Route as LocationsKingWilliamRouteImport } from './routes/locations/king-william'
import { Route as LocationsKingGeorgeRouteImport } from './routes/locations/king-george'
import { Route as LocationsHopewellRouteImport } from './routes/locations/hopewell'
import { Route as LocationsHenricoRouteImport } from './routes/locations/henrico'
import { Route as LocationsHanoverRouteImport } from './routes/locations/hanover'
import { Route as LocationsHamptonRouteImport } from './routes/locations/hampton'
import { Route as LocationsGoochlandRouteImport } from './routes/locations/goochland'
import { Route as LocationsGlenAllenRouteImport } from './routes/locations/glen-allen'
import { Route as LocationsFredericksburgRouteImport } from './routes/locations/fredericksburg'
import { Route as LocationsFluvannaRouteImport } from './routes/locations/fluvanna'
import { Route as LocationsDinwiddieRouteImport } from './routes/locations/dinwiddie'
import { Route as LocationsCumberlandRouteImport } from './routes/locations/cumberland'
import { Route as LocationsCulpeperRouteImport } from './routes/locations/culpeper'
import { Route as LocationsColonialHeightsRouteImport } from './routes/locations/colonial-heights'
import { Route as LocationsChesterfieldRouteImport } from './routes/locations/chesterfield'
import { Route as LocationsChesterRouteImport } from './routes/locations/chester'
import { Route as LocationsChesapeakeRouteImport } from './routes/locations/chesapeake'
import { Route as LocationsCharlesCityRouteImport } from './routes/locations/charles-city'
import { Route as LocationsCarolineRouteImport } from './routes/locations/caroline'
import { Route as LocationsBonAirRouteImport } from './routes/locations/bon-air'
import { Route as LocationsAshlandRouteImport } from './routes/locations/ashland'
import { Route as LocationsAmeliaRouteImport } from './routes/locations/amelia'

const WhaleHunterRoute = WhaleHunterRouteImport.update({
  id: '/whale-hunter',
  path: '/whale-hunter',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIntelRoute = WeatherIntelRouteImport.update({
  id: '/weather-intel',
  path: '/weather-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SealcoatingRoute = SealcoatingRouteImport.update({
  id: '/sealcoating',
  path: '/sealcoating',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofingRoute = RoofingRouteImport.update({
  id: '/roofing',
  path: '/roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialRoute = ResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MasonryRoute = MasonryRouteImport.update({
  id: '/masonry',
  path: '/masonry',
  getParentRoute: () => rootRouteImport,
} as any)
const GcBidRoute = GcBidRouteImport.update({
  id: '/gc-bid',
  path: '/gc-bid',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcreteRoute = ConcreteRouteImport.update({
  id: '/concrete',
  path: '/concrete',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsWindsorFarmsRoute = LocationsWindsorFarmsRouteImport.update({
  id: '/locations/windsor-farms',
  path: '/locations/windsor-farms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsWilliamsburgRoute = LocationsWilliamsburgRouteImport.update({
  id: '/locations/williamsburg',
  path: '/locations/williamsburg',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsWesthamParkwayRoute = LocationsWesthamParkwayRouteImport.update({
  id: '/locations/westham-parkway',
  path: '/locations/westham-parkway',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsWarrentonRoute = LocationsWarrentonRouteImport.update({
  id: '/locations/warrenton',
  path: '/locations/warrenton',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsVirginiaBeachRoute = LocationsVirginiaBeachRouteImport.update({
  id: '/locations/virginia-beach',
  path: '/locations/virginia-beach',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsTuckahoeRoute = LocationsTuckahoeRouteImport.update({
  id: '/locations/tuckahoe',
  path: '/locations/tuckahoe',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSussexRoute = LocationsSussexRouteImport.update({
  id: '/locations/sussex',
  path: '/locations/sussex',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSuffolkRoute = LocationsSuffolkRouteImport.update({
  id: '/locations/suffolk',
  path: '/locations/suffolk',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsStratfordHillsRoute = LocationsStratfordHillsRouteImport.update({
  id: '/locations/stratford-hills',
  path: '/locations/stratford-hills',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsStandardsRoute = LocationsStandardsRouteImport.update({
  id: '/locations/standards',
  path: '/locations/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsStaffordRoute = LocationsStaffordRouteImport.update({
  id: '/locations/stafford',
  path: '/locations/stafford',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSpotsylvaniaRoute = LocationsSpotsylvaniaRouteImport.update({
  id: '/locations/spotsylvania',
  path: '/locations/spotsylvania',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsShortPumpRoute = LocationsShortPumpRouteImport.update({
  id: '/locations/short-pump',
  path: '/locations/short-pump',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSandstonRoute = LocationsSandstonRouteImport.update({
  id: '/locations/sandston',
  path: '/locations/sandston',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRichmondRoute = LocationsRichmondRouteImport.update({
  id: '/locations/richmond',
  path: '/locations/richmond',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsResidentialRoute = LocationsResidentialRouteImport.update({
  id: '/locations/residential',
  path: '/locations/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPrinceWilliamRoute = LocationsPrinceWilliamRouteImport.update({
  id: '/locations/prince-william',
  path: '/locations/prince-william',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPrinceGeorgeRoute = LocationsPrinceGeorgeRouteImport.update({
  id: '/locations/prince-george',
  path: '/locations/prince-george',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPowhatanRoute = LocationsPowhatanRouteImport.update({
  id: '/locations/powhatan',
  path: '/locations/powhatan',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPortsmouthRoute = LocationsPortsmouthRouteImport.update({
  id: '/locations/portsmouth',
  path: '/locations/portsmouth',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPetersburgRoute = LocationsPetersburgRouteImport.update({
  id: '/locations/petersburg',
  path: '/locations/petersburg',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsOrangeRoute = LocationsOrangeRouteImport.update({
  id: '/locations/orange',
  path: '/locations/orange',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNorfolkRoute = LocationsNorfolkRouteImport.update({
  id: '/locations/norfolk',
  path: '/locations/norfolk',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNewportnewsRoute = LocationsNewportnewsRouteImport.update({
  id: '/locations/newportnews',
  path: '/locations/newportnews',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNewKentRoute = LocationsNewKentRouteImport.update({
  id: '/locations/new-kent',
  path: '/locations/new-kent',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMoseleyRoute = LocationsMoseleyRouteImport.update({
  id: '/locations/moseley',
  path: '/locations/moseley',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMidlothianRoute = LocationsMidlothianRouteImport.update({
  id: '/locations/midlothian',
  path: '/locations/midlothian',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMechanicsvilleRoute = LocationsMechanicsvilleRouteImport.update({
  id: '/locations/mechanicsville',
  path: '/locations/mechanicsville',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMcleanRoute = LocationsMcleanRouteImport.update({
  id: '/locations/mclean',
  path: '/locations/mclean',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLouisaRoute = LocationsLouisaRouteImport.update({
  id: '/locations/louisa',
  path: '/locations/louisa',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLakesideRoute = LocationsLakesideRouteImport.update({
  id: '/locations/lakeside',
  path: '/locations/lakeside',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsKingWilliamRoute = LocationsKingWilliamRouteImport.update({
  id: '/locations/king-william',
  path: '/locations/king-william',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsKingGeorgeRoute = LocationsKingGeorgeRouteImport.update({
  id: '/locations/king-george',
  path: '/locations/king-george',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsHopewellRoute = LocationsHopewellRouteImport.update({
  id: '/locations/hopewell',
  path: '/locations/hopewell',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsHenricoRoute = LocationsHenricoRouteImport.update({
  id: '/locations/henrico',
  path: '/locations/henrico',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsHanoverRoute = LocationsHanoverRouteImport.update({
  id: '/locations/hanover',
  path: '/locations/hanover',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsHamptonRoute = LocationsHamptonRouteImport.update({
  id: '/locations/hampton',
  path: '/locations/hampton',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsGoochlandRoute = LocationsGoochlandRouteImport.update({
  id: '/locations/goochland',
  path: '/locations/goochland',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsGlenAllenRoute = LocationsGlenAllenRouteImport.update({
  id: '/locations/glen-allen',
  path: '/locations/glen-allen',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsFredericksburgRoute = LocationsFredericksburgRouteImport.update({
  id: '/locations/fredericksburg',
  path: '/locations/fredericksburg',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsFluvannaRoute = LocationsFluvannaRouteImport.update({
  id: '/locations/fluvanna',
  path: '/locations/fluvanna',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsDinwiddieRoute = LocationsDinwiddieRouteImport.update({
  id: '/locations/dinwiddie',
  path: '/locations/dinwiddie',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCumberlandRoute = LocationsCumberlandRouteImport.update({
  id: '/locations/cumberland',
  path: '/locations/cumberland',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCulpeperRoute = LocationsCulpeperRouteImport.update({
  id: '/locations/culpeper',
  path: '/locations/culpeper',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsColonialHeightsRoute =
  LocationsColonialHeightsRouteImport.update({
    id: '/locations/colonial-heights',
    path: '/locations/colonial-heights',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsChesterfieldRoute = LocationsChesterfieldRouteImport.update({
  id: '/locations/chesterfield',
  path: '/locations/chesterfield',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsChesterRoute = LocationsChesterRouteImport.update({
  id: '/locations/chester',
  path: '/locations/chester',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsChesapeakeRoute = LocationsChesapeakeRouteImport.update({
  id: '/locations/chesapeake',
  path: '/locations/chesapeake',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCharlesCityRoute = LocationsCharlesCityRouteImport.update({
  id: '/locations/charles-city',
  path: '/locations/charles-city',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCarolineRoute = LocationsCarolineRouteImport.update({
  id: '/locations/caroline',
  path: '/locations/caroline',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsBonAirRoute = LocationsBonAirRouteImport.update({
  id: '/locations/bon-air',
  path: '/locations/bon-air',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsAshlandRoute = LocationsAshlandRouteImport.update({
  id: '/locations/ashland',
  path: '/locations/ashland',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsAmeliaRoute = LocationsAmeliaRouteImport.update({
  id: '/locations/amelia',
  path: '/locations/amelia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/concrete': typeof ConcreteRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRoute
  '/gallery': typeof GalleryRoute
  '/gc-bid': typeof GcBidRoute
  '/masonry': typeof MasonryRoute
  '/portal': typeof PortalRoute
  '/residential': typeof ResidentialRoute
  '/roofing': typeof RoofingRoute
  '/safety': typeof SafetyRoute
  '/sealcoating': typeof SealcoatingRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/weather-intel': typeof WeatherIntelRoute
  '/whale-hunter': typeof WhaleHunterRoute
  '/locations/amelia': typeof LocationsAmeliaRoute
  '/locations/ashland': typeof LocationsAshlandRoute
  '/locations/bon-air': typeof LocationsBonAirRoute
  '/locations/caroline': typeof LocationsCarolineRoute
  '/locations/charles-city': typeof LocationsCharlesCityRoute
  '/locations/chesapeake': typeof LocationsChesapeakeRoute
  '/locations/chester': typeof LocationsChesterRoute
  '/locations/chesterfield': typeof LocationsChesterfieldRoute
  '/locations/colonial-heights': typeof LocationsColonialHeightsRoute
  '/locations/culpeper': typeof LocationsCulpeperRoute
  '/locations/cumberland': typeof LocationsCumberlandRoute
  '/locations/dinwiddie': typeof LocationsDinwiddieRoute
  '/locations/fluvanna': typeof LocationsFluvannaRoute
  '/locations/fredericksburg': typeof LocationsFredericksburgRoute
  '/locations/glen-allen': typeof LocationsGlenAllenRoute
  '/locations/goochland': typeof LocationsGoochlandRoute
  '/locations/hampton': typeof LocationsHamptonRoute
  '/locations/hanover': typeof LocationsHanoverRoute
  '/locations/henrico': typeof LocationsHenricoRoute
  '/locations/hopewell': typeof LocationsHopewellRoute
  '/locations/king-george': typeof LocationsKingGeorgeRoute
  '/locations/king-william': typeof LocationsKingWilliamRoute
  '/locations/lakeside': typeof LocationsLakesideRoute
  '/locations/louisa': typeof LocationsLouisaRoute
  '/locations/mclean': typeof LocationsMcleanRoute
  '/locations/mechanicsville': typeof LocationsMechanicsvilleRoute
  '/locations/midlothian': typeof LocationsMidlothianRoute
  '/locations/moseley': typeof LocationsMoseleyRoute
  '/locations/new-kent': typeof LocationsNewKentRoute
  '/locations/newportnews': typeof LocationsNewportnewsRoute
  '/locations/norfolk': typeof LocationsNorfolkRoute
  '/locations/orange': typeof LocationsOrangeRoute
  '/locations/petersburg': typeof LocationsPetersburgRoute
  '/locations/portsmouth': typeof LocationsPortsmouthRoute
  '/locations/powhatan': typeof LocationsPowhatanRoute
  '/locations/prince-george': typeof LocationsPrinceGeorgeRoute
  '/locations/prince-william': typeof LocationsPrinceWilliamRoute
  '/locations/residential': typeof LocationsResidentialRoute
  '/locations/richmond': typeof LocationsRichmondRoute
  '/locations/sandston': typeof LocationsSandstonRoute
  '/locations/short-pump': typeof LocationsShortPumpRoute
  '/locations/spotsylvania': typeof LocationsSpotsylvaniaRoute
  '/locations/stafford': typeof LocationsStaffordRoute
  '/locations/standards': typeof LocationsStandardsRoute
  '/locations/stratford-hills': typeof LocationsStratfordHillsRoute
  '/locations/suffolk': typeof LocationsSuffolkRoute
  '/locations/sussex': typeof LocationsSussexRoute
  '/locations/tuckahoe': typeof LocationsTuckahoeRoute
  '/locations/virginia-beach': typeof LocationsVirginiaBeachRoute
  '/locations/warrenton': typeof LocationsWarrentonRoute
  '/locations/westham-parkway': typeof LocationsWesthamParkwayRoute
  '/locations/williamsburg': typeof LocationsWilliamsburgRoute
  '/locations/windsor-farms': typeof LocationsWindsorFarmsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/concrete': typeof ConcreteRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRoute
  '/gallery': typeof GalleryRoute
  '/gc-bid': typeof GcBidRoute
  '/masonry': typeof MasonryRoute
  '/portal': typeof PortalRoute
  '/residential': typeof ResidentialRoute
  '/roofing': typeof RoofingRoute
  '/safety': typeof SafetyRoute
  '/sealcoating': typeof SealcoatingRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/weather-intel': typeof WeatherIntelRoute
  '/whale-hunter': typeof WhaleHunterRoute
  '/locations/amelia': typeof LocationsAmeliaRoute
  '/locations/ashland': typeof LocationsAshlandRoute
  '/locations/bon-air': typeof LocationsBonAirRoute
  '/locations/caroline': typeof LocationsCarolineRoute
  '/locations/charles-city': typeof LocationsCharlesCityRoute
  '/locations/chesapeake': typeof LocationsChesapeakeRoute
  '/locations/chester': typeof LocationsChesterRoute
  '/locations/chesterfield': typeof LocationsChesterfieldRoute
  '/locations/colonial-heights': typeof LocationsColonialHeightsRoute
  '/locations/culpeper': typeof LocationsCulpeperRoute
  '/locations/cumberland': typeof LocationsCumberlandRoute
  '/locations/dinwiddie': typeof LocationsDinwiddieRoute
  '/locations/fluvanna': typeof LocationsFluvannaRoute
  '/locations/fredericksburg': typeof LocationsFredericksburgRoute
  '/locations/glen-allen': typeof LocationsGlenAllenRoute
  '/locations/goochland': typeof LocationsGoochlandRoute
  '/locations/hampton': typeof LocationsHamptonRoute
  '/locations/hanover': typeof LocationsHanoverRoute
  '/locations/henrico': typeof LocationsHenricoRoute
  '/locations/hopewell': typeof LocationsHopewellRoute
  '/locations/king-george': typeof LocationsKingGeorgeRoute
  '/locations/king-william': typeof LocationsKingWilliamRoute
  '/locations/lakeside': typeof LocationsLakesideRoute
  '/locations/louisa': typeof LocationsLouisaRoute
  '/locations/mclean': typeof LocationsMcleanRoute
  '/locations/mechanicsville': typeof LocationsMechanicsvilleRoute
  '/locations/midlothian': typeof LocationsMidlothianRoute
  '/locations/moseley': typeof LocationsMoseleyRoute
  '/locations/new-kent': typeof LocationsNewKentRoute
  '/locations/newportnews': typeof LocationsNewportnewsRoute
  '/locations/norfolk': typeof LocationsNorfolkRoute
  '/locations/orange': typeof LocationsOrangeRoute
  '/locations/petersburg': typeof LocationsPetersburgRoute
  '/locations/portsmouth': typeof LocationsPortsmouthRoute
  '/locations/powhatan': typeof LocationsPowhatanRoute
  '/locations/prince-george': typeof LocationsPrinceGeorgeRoute
  '/locations/prince-william': typeof LocationsPrinceWilliamRoute
  '/locations/residential': typeof LocationsResidentialRoute
  '/locations/richmond': typeof LocationsRichmondRoute
  '/locations/sandston': typeof LocationsSandstonRoute
  '/locations/short-pump': typeof LocationsShortPumpRoute
  '/locations/spotsylvania': typeof LocationsSpotsylvaniaRoute
  '/locations/stafford': typeof LocationsStaffordRoute
  '/locations/standards': typeof LocationsStandardsRoute
  '/locations/stratford-hills': typeof LocationsStratfordHillsRoute
  '/locations/suffolk': typeof LocationsSuffolkRoute
  '/locations/sussex': typeof LocationsSussexRoute
  '/locations/tuckahoe': typeof LocationsTuckahoeRoute
  '/locations/virginia-beach': typeof LocationsVirginiaBeachRoute
  '/locations/warrenton': typeof LocationsWarrentonRoute
  '/locations/westham-parkway': typeof LocationsWesthamParkwayRoute
  '/locations/williamsburg': typeof LocationsWilliamsburgRoute
  '/locations/windsor-farms': typeof LocationsWindsorFarmsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/concrete': typeof ConcreteRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRoute
  '/gallery': typeof GalleryRoute
  '/gc-bid': typeof GcBidRoute
  '/masonry': typeof MasonryRoute
  '/portal': typeof PortalRoute
  '/residential': typeof ResidentialRoute
  '/roofing': typeof RoofingRoute
  '/safety': typeof SafetyRoute
  '/sealcoating': typeof SealcoatingRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/weather-intel': typeof WeatherIntelRoute
  '/whale-hunter': typeof WhaleHunterRoute
  '/locations/amelia': typeof LocationsAmeliaRoute
  '/locations/ashland': typeof LocationsAshlandRoute
  '/locations/bon-air': typeof LocationsBonAirRoute
  '/locations/caroline': typeof LocationsCarolineRoute
  '/locations/charles-city': typeof LocationsCharlesCityRoute
  '/locations/chesapeake': typeof LocationsChesapeakeRoute
  '/locations/chester': typeof LocationsChesterRoute
  '/locations/chesterfield': typeof LocationsChesterfieldRoute
  '/locations/colonial-heights': typeof LocationsColonialHeightsRoute
  '/locations/culpeper': typeof LocationsCulpeperRoute
  '/locations/cumberland': typeof LocationsCumberlandRoute
  '/locations/dinwiddie': typeof LocationsDinwiddieRoute
  '/locations/fluvanna': typeof LocationsFluvannaRoute
  '/locations/fredericksburg': typeof LocationsFredericksburgRoute
  '/locations/glen-allen': typeof LocationsGlenAllenRoute
  '/locations/goochland': typeof LocationsGoochlandRoute
  '/locations/hampton': typeof LocationsHamptonRoute
  '/locations/hanover': typeof LocationsHanoverRoute
  '/locations/henrico': typeof LocationsHenricoRoute
  '/locations/hopewell': typeof LocationsHopewellRoute
  '/locations/king-george': typeof LocationsKingGeorgeRoute
  '/locations/king-william': typeof LocationsKingWilliamRoute
  '/locations/lakeside': typeof LocationsLakesideRoute
  '/locations/louisa': typeof LocationsLouisaRoute
  '/locations/mclean': typeof LocationsMcleanRoute
  '/locations/mechanicsville': typeof LocationsMechanicsvilleRoute
  '/locations/midlothian': typeof LocationsMidlothianRoute
  '/locations/moseley': typeof LocationsMoseleyRoute
  '/locations/new-kent': typeof LocationsNewKentRoute
  '/locations/newportnews': typeof LocationsNewportnewsRoute
  '/locations/norfolk': typeof LocationsNorfolkRoute
  '/locations/orange': typeof LocationsOrangeRoute
  '/locations/petersburg': typeof LocationsPetersburgRoute
  '/locations/portsmouth': typeof LocationsPortsmouthRoute
  '/locations/powhatan': typeof LocationsPowhatanRoute
  '/locations/prince-george': typeof LocationsPrinceGeorgeRoute
  '/locations/prince-william': typeof LocationsPrinceWilliamRoute
  '/locations/residential': typeof LocationsResidentialRoute
  '/locations/richmond': typeof LocationsRichmondRoute
  '/locations/sandston': typeof LocationsSandstonRoute
  '/locations/short-pump': typeof LocationsShortPumpRoute
  '/locations/spotsylvania': typeof LocationsSpotsylvaniaRoute
  '/locations/stafford': typeof LocationsStaffordRoute
  '/locations/standards': typeof LocationsStandardsRoute
  '/locations/stratford-hills': typeof LocationsStratfordHillsRoute
  '/locations/suffolk': typeof LocationsSuffolkRoute
  '/locations/sussex': typeof LocationsSussexRoute
  '/locations/tuckahoe': typeof LocationsTuckahoeRoute
  '/locations/virginia-beach': typeof LocationsVirginiaBeachRoute
  '/locations/warrenton': typeof LocationsWarrentonRoute
  '/locations/westham-parkway': typeof LocationsWesthamParkwayRoute
  '/locations/williamsburg': typeof LocationsWilliamsburgRoute
  '/locations/windsor-farms': typeof LocationsWindsorFarmsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commercial'
    | '/concrete'
    | '/contact'
    | '/estimator'
    | '/gallery'
    | '/gc-bid'
    | '/masonry'
    | '/portal'
    | '/residential'
    | '/roofing'
    | '/safety'
    | '/sealcoating'
    | '/services'
    | '/standards'
    | '/weather-intel'
    | '/whale-hunter'
    | '/locations/amelia'
    | '/locations/ashland'
    | '/locations/bon-air'
    | '/locations/caroline'
    | '/locations/charles-city'
    | '/locations/chesapeake'
    | '/locations/chester'
    | '/locations/chesterfield'
    | '/locations/colonial-heights'
    | '/locations/culpeper'
    | '/locations/cumberland'
    | '/locations/dinwiddie'
    | '/locations/fluvanna'
    | '/locations/fredericksburg'
    | '/locations/glen-allen'
    | '/locations/goochland'
    | '/locations/hampton'
    | '/locations/hanover'
    | '/locations/henrico'
    | '/locations/hopewell'
    | '/locations/king-george'
    | '/locations/king-william'
    | '/locations/lakeside'
    | '/locations/louisa'
    | '/locations/mclean'
    | '/locations/mechanicsville'
    | '/locations/midlothian'
    | '/locations/moseley'
    | '/locations/new-kent'
    | '/locations/newportnews'
    | '/locations/norfolk'
    | '/locations/orange'
    | '/locations/petersburg'
    | '/locations/portsmouth'
    | '/locations/powhatan'
    | '/locations/prince-george'
    | '/locations/prince-william'
    | '/locations/residential'
    | '/locations/richmond'
    | '/locations/sandston'
    | '/locations/short-pump'
    | '/locations/spotsylvania'
    | '/locations/stafford'
    | '/locations/standards'
    | '/locations/stratford-hills'
    | '/locations/suffolk'
    | '/locations/sussex'
    | '/locations/tuckahoe'
    | '/locations/virginia-beach'
    | '/locations/warrenton'
    | '/locations/westham-parkway'
    | '/locations/williamsburg'
    | '/locations/windsor-farms'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial'
    | '/concrete'
    | '/contact'
    | '/estimator'
    | '/gallery'
    | '/gc-bid'
    | '/masonry'
    | '/portal'
    | '/residential'
    | '/roofing'
    | '/safety'
    | '/sealcoating'
    | '/services'
    | '/standards'
    | '/weather-intel'
    | '/whale-hunter'
    | '/locations/amelia'
    | '/locations/ashland'
    | '/locations/bon-air'
    | '/locations/caroline'
    | '/locations/charles-city'
    | '/locations/chesapeake'
    | '/locations/chester'
    | '/locations/chesterfield'
    | '/locations/colonial-heights'
    | '/locations/culpeper'
    | '/locations/cumberland'
    | '/locations/dinwiddie'
    | '/locations/fluvanna'
    | '/locations/fredericksburg'
    | '/locations/glen-allen'
    | '/locations/goochland'
    | '/locations/hampton'
    | '/locations/hanover'
    | '/locations/henrico'
    | '/locations/hopewell'
    | '/locations/king-george'
    | '/locations/king-william'
    | '/locations/lakeside'
    | '/locations/louisa'
    | '/locations/mclean'
    | '/locations/mechanicsville'
    | '/locations/midlothian'
    | '/locations/moseley'
    | '/locations/new-kent'
    | '/locations/newportnews'
    | '/locations/norfolk'
    | '/locations/orange'
    | '/locations/petersburg'
    | '/locations/portsmouth'
    | '/locations/powhatan'
    | '/locations/prince-george'
    | '/locations/prince-william'
    | '/locations/residential'
    | '/locations/richmond'
    | '/locations/sandston'
    | '/locations/short-pump'
    | '/locations/spotsylvania'
    | '/locations/stafford'
    | '/locations/standards'
    | '/locations/stratford-hills'
    | '/locations/suffolk'
    | '/locations/sussex'
    | '/locations/tuckahoe'
    | '/locations/virginia-beach'
    | '/locations/warrenton'
    | '/locations/westham-parkway'
    | '/locations/williamsburg'
    | '/locations/windsor-farms'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commercial'
    | '/concrete'
    | '/contact'
    | '/estimator'
    | '/gallery'
    | '/gc-bid'
    | '/masonry'
    | '/portal'
    | '/residential'
    | '/roofing'
    | '/safety'
    | '/sealcoating'
    | '/services'
    | '/standards'
    | '/weather-intel'
    | '/whale-hunter'
    | '/locations/amelia'
    | '/locations/ashland'
    | '/locations/bon-air'
    | '/locations/caroline'
    | '/locations/charles-city'
    | '/locations/chesapeake'
    | '/locations/chester'
    | '/locations/chesterfield'
    | '/locations/colonial-heights'
    | '/locations/culpeper'
    | '/locations/cumberland'
    | '/locations/dinwiddie'
    | '/locations/fluvanna'
    | '/locations/fredericksburg'
    | '/locations/glen-allen'
    | '/locations/goochland'
    | '/locations/hampton'
    | '/locations/hanover'
    | '/locations/henrico'
    | '/locations/hopewell'
    | '/locations/king-george'
    | '/locations/king-william'
    | '/locations/lakeside'
    | '/locations/louisa'
    | '/locations/mclean'
    | '/locations/mechanicsville'
    | '/locations/midlothian'
    | '/locations/moseley'
    | '/locations/new-kent'
    | '/locations/newportnews'
    | '/locations/norfolk'
    | '/locations/orange'
    | '/locations/petersburg'
    | '/locations/portsmouth'
    | '/locations/powhatan'
    | '/locations/prince-george'
    | '/locations/prince-william'
    | '/locations/residential'
    | '/locations/richmond'
    | '/locations/sandston'
    | '/locations/short-pump'
    | '/locations/spotsylvania'
    | '/locations/stafford'
    | '/locations/standards'
    | '/locations/stratford-hills'
    | '/locations/suffolk'
    | '/locations/sussex'
    | '/locations/tuckahoe'
    | '/locations/virginia-beach'
    | '/locations/warrenton'
    | '/locations/westham-parkway'
    | '/locations/williamsburg'
    | '/locations/windsor-farms'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommercialRoute: typeof CommercialRoute
  ConcreteRoute: typeof ConcreteRoute
  ContactRoute: typeof ContactRoute
  EstimatorRoute: typeof EstimatorRoute
  GalleryRoute: typeof GalleryRoute
  GcBidRoute: typeof GcBidRoute
  MasonryRoute: typeof MasonryRoute
  PortalRoute: typeof PortalRoute
  ResidentialRoute: typeof ResidentialRoute
  RoofingRoute: typeof RoofingRoute
  SafetyRoute: typeof SafetyRoute
  SealcoatingRoute: typeof SealcoatingRoute
  ServicesRoute: typeof ServicesRoute
  StandardsRoute: typeof StandardsRoute
  WeatherIntelRoute: typeof WeatherIntelRoute
  WhaleHunterRoute: typeof WhaleHunterRoute
  LocationsAmeliaRoute: typeof LocationsAmeliaRoute
  LocationsAshlandRoute: typeof LocationsAshlandRoute
  LocationsBonAirRoute: typeof LocationsBonAirRoute
  LocationsCarolineRoute: typeof LocationsCarolineRoute
  LocationsCharlesCityRoute: typeof LocationsCharlesCityRoute
  LocationsChesapeakeRoute: typeof LocationsChesapeakeRoute
  LocationsChesterRoute: typeof LocationsChesterRoute
  LocationsChesterfieldRoute: typeof LocationsChesterfieldRoute
  LocationsColonialHeightsRoute: typeof LocationsColonialHeightsRoute
  LocationsCulpeperRoute: typeof LocationsCulpeperRoute
  LocationsCumberlandRoute: typeof LocationsCumberlandRoute
  LocationsDinwiddieRoute: typeof LocationsDinwiddieRoute
  LocationsFluvannaRoute: typeof LocationsFluvannaRoute
  LocationsFredericksburgRoute: typeof LocationsFredericksburgRoute
  LocationsGlenAllenRoute: typeof LocationsGlenAllenRoute
  LocationsGoochlandRoute: typeof LocationsGoochlandRoute
  LocationsHamptonRoute: typeof LocationsHamptonRoute
  LocationsHanoverRoute: typeof LocationsHanoverRoute
  LocationsHenricoRoute: typeof LocationsHenricoRoute
  LocationsHopewellRoute: typeof LocationsHopewellRoute
  LocationsKingGeorgeRoute: typeof LocationsKingGeorgeRoute
  LocationsKingWilliamRoute: typeof LocationsKingWilliamRoute
  LocationsLakesideRoute: typeof LocationsLakesideRoute
  LocationsLouisaRoute: typeof LocationsLouisaRoute
  LocationsMcleanRoute: typeof LocationsMcleanRoute
  LocationsMechanicsvilleRoute: typeof LocationsMechanicsvilleRoute
  LocationsMidlothianRoute: typeof LocationsMidlothianRoute
  LocationsMoseleyRoute: typeof LocationsMoseleyRoute
  LocationsNewKentRoute: typeof LocationsNewKentRoute
  LocationsNewportnewsRoute: typeof LocationsNewportnewsRoute
  LocationsNorfolkRoute: typeof LocationsNorfolkRoute
  LocationsOrangeRoute: typeof LocationsOrangeRoute
  LocationsPetersburgRoute: typeof LocationsPetersburgRoute
  LocationsPortsmouthRoute: typeof LocationsPortsmouthRoute
  LocationsPowhatanRoute: typeof LocationsPowhatanRoute
  LocationsPrinceGeorgeRoute: typeof LocationsPrinceGeorgeRoute
  LocationsPrinceWilliamRoute: typeof LocationsPrinceWilliamRoute
  LocationsResidentialRoute: typeof LocationsResidentialRoute
  LocationsRichmondRoute: typeof LocationsRichmondRoute
  LocationsSandstonRoute: typeof LocationsSandstonRoute
  LocationsShortPumpRoute: typeof LocationsShortPumpRoute
  LocationsSpotsylvaniaRoute: typeof LocationsSpotsylvaniaRoute
  LocationsStaffordRoute: typeof LocationsStaffordRoute
  LocationsStandardsRoute: typeof LocationsStandardsRoute
  LocationsStratfordHillsRoute: typeof LocationsStratfordHillsRoute
  LocationsSuffolkRoute: typeof LocationsSuffolkRoute
  LocationsSussexRoute: typeof LocationsSussexRoute
  LocationsTuckahoeRoute: typeof LocationsTuckahoeRoute
  LocationsVirginiaBeachRoute: typeof LocationsVirginiaBeachRoute
  LocationsWarrentonRoute: typeof LocationsWarrentonRoute
  LocationsWesthamParkwayRoute: typeof LocationsWesthamParkwayRoute
  LocationsWilliamsburgRoute: typeof LocationsWilliamsburgRoute
  LocationsWindsorFarmsRoute: typeof LocationsWindsorFarmsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whale-hunter': {
      id: '/whale-hunter'
      path: '/whale-hunter'
      fullPath: '/whale-hunter'
      preLoaderRoute: typeof WhaleHunterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather-intel': {
      id: '/weather-intel'
      path: '/weather-intel'
      fullPath: '/weather-intel'
      preLoaderRoute: typeof WeatherIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sealcoating': {
      id: '/sealcoating'
      path: '/sealcoating'
      fullPath: '/sealcoating'
      preLoaderRoute: typeof SealcoatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofing': {
      id: '/roofing'
      path: '/roofing'
      fullPath: '/roofing'
      preLoaderRoute: typeof RoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential': {
      id: '/residential'
      path: '/residential'
      fullPath: '/residential'
      preLoaderRoute: typeof ResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masonry': {
      id: '/masonry'
      path: '/masonry'
      fullPath: '/masonry'
      preLoaderRoute: typeof MasonryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gc-bid': {
      id: '/gc-bid'
      path: '/gc-bid'
      fullPath: '/gc-bid'
      preLoaderRoute: typeof GcBidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concrete': {
      id: '/concrete'
      path: '/concrete'
      fullPath: '/concrete'
      preLoaderRoute: typeof ConcreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/windsor-farms': {
      id: '/locations/windsor-farms'
      path: '/locations/windsor-farms'
      fullPath: '/locations/windsor-farms'
      preLoaderRoute: typeof LocationsWindsorFarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/williamsburg': {
      id: '/locations/williamsburg'
      path: '/locations/williamsburg'
      fullPath: '/locations/williamsburg'
      preLoaderRoute: typeof LocationsWilliamsburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/westham-parkway': {
      id: '/locations/westham-parkway'
      path: '/locations/westham-parkway'
      fullPath: '/locations/westham-parkway'
      preLoaderRoute: typeof LocationsWesthamParkwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/warrenton': {
      id: '/locations/warrenton'
      path: '/locations/warrenton'
      fullPath: '/locations/warrenton'
      preLoaderRoute: typeof LocationsWarrentonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/virginia-beach': {
      id: '/locations/virginia-beach'
      path: '/locations/virginia-beach'
      fullPath: '/locations/virginia-beach'
      preLoaderRoute: typeof LocationsVirginiaBeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/tuckahoe': {
      id: '/locations/tuckahoe'
      path: '/locations/tuckahoe'
      fullPath: '/locations/tuckahoe'
      preLoaderRoute: typeof LocationsTuckahoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/sussex': {
      id: '/locations/sussex'
      path: '/locations/sussex'
      fullPath: '/locations/sussex'
      preLoaderRoute: typeof LocationsSussexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/suffolk': {
      id: '/locations/suffolk'
      path: '/locations/suffolk'
      fullPath: '/locations/suffolk'
      preLoaderRoute: typeof LocationsSuffolkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/stratford-hills': {
      id: '/locations/stratford-hills'
      path: '/locations/stratford-hills'
      fullPath: '/locations/stratford-hills'
      preLoaderRoute: typeof LocationsStratfordHillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/standards': {
      id: '/locations/standards'
      path: '/locations/standards'
      fullPath: '/locations/standards'
      preLoaderRoute: typeof LocationsStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/stafford': {
      id: '/locations/stafford'
      path: '/locations/stafford'
      fullPath: '/locations/stafford'
      preLoaderRoute: typeof LocationsStaffordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/spotsylvania': {
      id: '/locations/spotsylvania'
      path: '/locations/spotsylvania'
      fullPath: '/locations/spotsylvania'
      preLoaderRoute: typeof LocationsSpotsylvaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/short-pump': {
      id: '/locations/short-pump'
      path: '/locations/short-pump'
      fullPath: '/locations/short-pump'
      preLoaderRoute: typeof LocationsShortPumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/sandston': {
      id: '/locations/sandston'
      path: '/locations/sandston'
      fullPath: '/locations/sandston'
      preLoaderRoute: typeof LocationsSandstonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/richmond': {
      id: '/locations/richmond'
      path: '/locations/richmond'
      fullPath: '/locations/richmond'
      preLoaderRoute: typeof LocationsRichmondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/residential': {
      id: '/locations/residential'
      path: '/locations/residential'
      fullPath: '/locations/residential'
      preLoaderRoute: typeof LocationsResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/prince-william': {
      id: '/locations/prince-william'
      path: '/locations/prince-william'
      fullPath: '/locations/prince-william'
      preLoaderRoute: typeof LocationsPrinceWilliamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/prince-george': {
      id: '/locations/prince-george'
      path: '/locations/prince-george'
      fullPath: '/locations/prince-george'
      preLoaderRoute: typeof LocationsPrinceGeorgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/powhatan': {
      id: '/locations/powhatan'
      path: '/locations/powhatan'
      fullPath: '/locations/powhatan'
      preLoaderRoute: typeof LocationsPowhatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/portsmouth': {
      id: '/locations/portsmouth'
      path: '/locations/portsmouth'
      fullPath: '/locations/portsmouth'
      preLoaderRoute: typeof LocationsPortsmouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/petersburg': {
      id: '/locations/petersburg'
      path: '/locations/petersburg'
      fullPath: '/locations/petersburg'
      preLoaderRoute: typeof LocationsPetersburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/orange': {
      id: '/locations/orange'
      path: '/locations/orange'
      fullPath: '/locations/orange'
      preLoaderRoute: typeof LocationsOrangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/norfolk': {
      id: '/locations/norfolk'
      path: '/locations/norfolk'
      fullPath: '/locations/norfolk'
      preLoaderRoute: typeof LocationsNorfolkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/newportnews': {
      id: '/locations/newportnews'
      path: '/locations/newportnews'
      fullPath: '/locations/newportnews'
      preLoaderRoute: typeof LocationsNewportnewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/new-kent': {
      id: '/locations/new-kent'
      path: '/locations/new-kent'
      fullPath: '/locations/new-kent'
      preLoaderRoute: typeof LocationsNewKentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/moseley': {
      id: '/locations/moseley'
      path: '/locations/moseley'
      fullPath: '/locations/moseley'
      preLoaderRoute: typeof LocationsMoseleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/midlothian': {
      id: '/locations/midlothian'
      path: '/locations/midlothian'
      fullPath: '/locations/midlothian'
      preLoaderRoute: typeof LocationsMidlothianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/mechanicsville': {
      id: '/locations/mechanicsville'
      path: '/locations/mechanicsville'
      fullPath: '/locations/mechanicsville'
      preLoaderRoute: typeof LocationsMechanicsvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/mclean': {
      id: '/locations/mclean'
      path: '/locations/mclean'
      fullPath: '/locations/mclean'
      preLoaderRoute: typeof LocationsMcleanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/louisa': {
      id: '/locations/louisa'
      path: '/locations/louisa'
      fullPath: '/locations/louisa'
      preLoaderRoute: typeof LocationsLouisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/lakeside': {
      id: '/locations/lakeside'
      path: '/locations/lakeside'
      fullPath: '/locations/lakeside'
      preLoaderRoute: typeof LocationsLakesideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/king-william': {
      id: '/locations/king-william'
      path: '/locations/king-william'
      fullPath: '/locations/king-william'
      preLoaderRoute: typeof LocationsKingWilliamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/king-george': {
      id: '/locations/king-george'
      path: '/locations/king-george'
      fullPath: '/locations/king-george'
      preLoaderRoute: typeof LocationsKingGeorgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/hopewell': {
      id: '/locations/hopewell'
      path: '/locations/hopewell'
      fullPath: '/locations/hopewell'
      preLoaderRoute: typeof LocationsHopewellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/henrico': {
      id: '/locations/henrico'
      path: '/locations/henrico'
      fullPath: '/locations/henrico'
      preLoaderRoute: typeof LocationsHenricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/hanover': {
      id: '/locations/hanover'
      path: '/locations/hanover'
      fullPath: '/locations/hanover'
      preLoaderRoute: typeof LocationsHanoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/hampton': {
      id: '/locations/hampton'
      path: '/locations/hampton'
      fullPath: '/locations/hampton'
      preLoaderRoute: typeof LocationsHamptonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/goochland': {
      id: '/locations/goochland'
      path: '/locations/goochland'
      fullPath: '/locations/goochland'
      preLoaderRoute: typeof LocationsGoochlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/glen-allen': {
      id: '/locations/glen-allen'
      path: '/locations/glen-allen'
      fullPath: '/locations/glen-allen'
      preLoaderRoute: typeof LocationsGlenAllenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/fredericksburg': {
      id: '/locations/fredericksburg'
      path: '/locations/fredericksburg'
      fullPath: '/locations/fredericksburg'
      preLoaderRoute: typeof LocationsFredericksburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/fluvanna': {
      id: '/locations/fluvanna'
      path: '/locations/fluvanna'
      fullPath: '/locations/fluvanna'
      preLoaderRoute: typeof LocationsFluvannaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/dinwiddie': {
      id: '/locations/dinwiddie'
      path: '/locations/dinwiddie'
      fullPath: '/locations/dinwiddie'
      preLoaderRoute: typeof LocationsDinwiddieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/cumberland': {
      id: '/locations/cumberland'
      path: '/locations/cumberland'
      fullPath: '/locations/cumberland'
      preLoaderRoute: typeof LocationsCumberlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/culpeper': {
      id: '/locations/culpeper'
      path: '/locations/culpeper'
      fullPath: '/locations/culpeper'
      preLoaderRoute: typeof LocationsCulpeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/colonial-heights': {
      id: '/locations/colonial-heights'
      path: '/locations/colonial-heights'
      fullPath: '/locations/colonial-heights'
      preLoaderRoute: typeof LocationsColonialHeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/chesterfield': {
      id: '/locations/chesterfield'
      path: '/locations/chesterfield'
      fullPath: '/locations/chesterfield'
      preLoaderRoute: typeof LocationsChesterfieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/chester': {
      id: '/locations/chester'
      path: '/locations/chester'
      fullPath: '/locations/chester'
      preLoaderRoute: typeof LocationsChesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/chesapeake': {
      id: '/locations/chesapeake'
      path: '/locations/chesapeake'
      fullPath: '/locations/chesapeake'
      preLoaderRoute: typeof LocationsChesapeakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/charles-city': {
      id: '/locations/charles-city'
      path: '/locations/charles-city'
      fullPath: '/locations/charles-city'
      preLoaderRoute: typeof LocationsCharlesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/caroline': {
      id: '/locations/caroline'
      path: '/locations/caroline'
      fullPath: '/locations/caroline'
      preLoaderRoute: typeof LocationsCarolineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/bon-air': {
      id: '/locations/bon-air'
      path: '/locations/bon-air'
      fullPath: '/locations/bon-air'
      preLoaderRoute: typeof LocationsBonAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/ashland': {
      id: '/locations/ashland'
      path: '/locations/ashland'
      fullPath: '/locations/ashland'
      preLoaderRoute: typeof LocationsAshlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/amelia': {
      id: '/locations/amelia'
      path: '/locations/amelia'
      fullPath: '/locations/amelia'
      preLoaderRoute: typeof LocationsAmeliaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommercialRoute: CommercialRoute,
  ConcreteRoute: ConcreteRoute,
  ContactRoute: ContactRoute,
  EstimatorRoute: EstimatorRoute,
  GalleryRoute: GalleryRoute,
  GcBidRoute: GcBidRoute,
  MasonryRoute: MasonryRoute,
  PortalRoute: PortalRoute,
  ResidentialRoute: ResidentialRoute,
  RoofingRoute: RoofingRoute,
  SafetyRoute: SafetyRoute,
  SealcoatingRoute: SealcoatingRoute,
  ServicesRoute: ServicesRoute,
  StandardsRoute: StandardsRoute,
  WeatherIntelRoute: WeatherIntelRoute,
  WhaleHunterRoute: WhaleHunterRoute,
  LocationsAmeliaRoute: LocationsAmeliaRoute,
  LocationsAshlandRoute: LocationsAshlandRoute,
  LocationsBonAirRoute: LocationsBonAirRoute,
  LocationsCarolineRoute: LocationsCarolineRoute,
  LocationsCharlesCityRoute: LocationsCharlesCityRoute,
  LocationsChesapeakeRoute: LocationsChesapeakeRoute,
  LocationsChesterRoute: LocationsChesterRoute,
  LocationsChesterfieldRoute: LocationsChesterfieldRoute,
  LocationsColonialHeightsRoute: LocationsColonialHeightsRoute,
  LocationsCulpeperRoute: LocationsCulpeperRoute,
  LocationsCumberlandRoute: LocationsCumberlandRoute,
  LocationsDinwiddieRoute: LocationsDinwiddieRoute,
  LocationsFluvannaRoute: LocationsFluvannaRoute,
  LocationsFredericksburgRoute: LocationsFredericksburgRoute,
  LocationsGlenAllenRoute: LocationsGlenAllenRoute,
  LocationsGoochlandRoute: LocationsGoochlandRoute,
  LocationsHamptonRoute: LocationsHamptonRoute,
  LocationsHanoverRoute: LocationsHanoverRoute,
  LocationsHenricoRoute: LocationsHenricoRoute,
  LocationsHopewellRoute: LocationsHopewellRoute,
  LocationsKingGeorgeRoute: LocationsKingGeorgeRoute,
  LocationsKingWilliamRoute: LocationsKingWilliamRoute,
  LocationsLakesideRoute: LocationsLakesideRoute,
  LocationsLouisaRoute: LocationsLouisaRoute,
  LocationsMcleanRoute: LocationsMcleanRoute,
  LocationsMechanicsvilleRoute: LocationsMechanicsvilleRoute,
  LocationsMidlothianRoute: LocationsMidlothianRoute,
  LocationsMoseleyRoute: LocationsMoseleyRoute,
  LocationsNewKentRoute: LocationsNewKentRoute,
  LocationsNewportnewsRoute: LocationsNewportnewsRoute,
  LocationsNorfolkRoute: LocationsNorfolkRoute,
  LocationsOrangeRoute: LocationsOrangeRoute,
  LocationsPetersburgRoute: LocationsPetersburgRoute,
  LocationsPortsmouthRoute: LocationsPortsmouthRoute,
  LocationsPowhatanRoute: LocationsPowhatanRoute,
  LocationsPrinceGeorgeRoute: LocationsPrinceGeorgeRoute,
  LocationsPrinceWilliamRoute: LocationsPrinceWilliamRoute,
  LocationsResidentialRoute: LocationsResidentialRoute,
  LocationsRichmondRoute: LocationsRichmondRoute,
  LocationsSandstonRoute: LocationsSandstonRoute,
  LocationsShortPumpRoute: LocationsShortPumpRoute,
  LocationsSpotsylvaniaRoute: LocationsSpotsylvaniaRoute,
  LocationsStaffordRoute: LocationsStaffordRoute,
  LocationsStandardsRoute: LocationsStandardsRoute,
  LocationsStratfordHillsRoute: LocationsStratfordHillsRoute,
  LocationsSuffolkRoute: LocationsSuffolkRoute,
  LocationsSussexRoute: LocationsSussexRoute,
  LocationsTuckahoeRoute: LocationsTuckahoeRoute,
  LocationsVirginiaBeachRoute: LocationsVirginiaBeachRoute,
  LocationsWarrentonRoute: LocationsWarrentonRoute,
  LocationsWesthamParkwayRoute: LocationsWesthamParkwayRoute,
  LocationsWilliamsburgRoute: LocationsWilliamsburgRoute,
  LocationsWindsorFarmsRoute: LocationsWindsorFarmsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
